# Bootstraps entire app, frontend, backend and supporting artifacts (persistence, etc)
# from images built for a production release
#
version: '3.3'
services:
  frontend:
    image: docker.io/mrazjava/booklink-frontend-vue:develop
    ports:
      - "8090:80"
    environment:
      VUE_APP_BACKEND_HOST: http://localhost:8080
      VUE_APP_ENV: stg
  backend:
    image: docker.io/mrazjava/booklink-backend:develop
    ports:
    - "8080:8080"
    environment:
      CORS_ALLOW_ORIGINS: http://localhost:8090
      APP_BE_DB_URL: jdbc:postgresql://pg:5432/booklink-stg
      APP_ENV: stg
  pg:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: booklink-stg
      POSTGRES_USER: bookworm
      POSTGRES_PASSWORD: BL
    ports:
      - 127.0.0.1:5432:5432