version: '3.3'

services:
  mongodb:
    image: mongo:4.2.8 # https://hub.docker.com/_/mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: openlibrary
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db
  pg:
    image: mrazjava/booklink-persistence:pg.12.2
    ports:
      - 127.0.0.1:5432:5432
  admin:
    image: dpage/pgadmin4 # https://hub.docker.com/r/dpage/pgadmin4/
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@docker # used as a login id
      PGADMIN_DEFAULT_PASSWORD: admin
      GUNICORN_ACCESS_LOGFILE: /tmp/pgadmin4.log
    ports:
      - 127.0.0.1:5500:80
#    logging:
#      driver: none
volumes:
  mongo-data: