# Bootstraps entire app, frontend, backend and supporting artifacts (persistence, etc)
# from images built for a production release
#
version: '3.3'
services:
  frontend:
    image: docker.io/mrazjava/booklink-frontend-vue:${FE_IMG_TAG}
    ports:
      - "8090:80"
    environment:
      FE_DEPLOY_ENV: local
      FE_DEPLOY_BE_HOST: http://localhost:8080
      FE_FB_APPID: 1662925783847528
      FE_GL_APPID: 1022797606973-5j5ppvnp01qbqcqhqn1p6umh6n84kvpf.apps.googleusercontent.com
      FE_SANDBOX: 1
      # backward-compatibility: <= v0.2.0
      VUE_APP_BACKEND_HOST: http://localhost:8080
      VUE_APP_ENV: stg
  backend:
    image: docker.io/mrazjava/booklink-backend:${BE_IMG_TAG}
    ports:
    - "8080:8080"
    environment:
      CORS_ALLOW_ORIGINS: http://localhost:8090
      APP_BE_DB_URL: jdbc:postgresql://pg:5432/booklink_sndbx_local
      APP_BE_HIBERNATE_DDL_AUTO: validate
      APP_SPRING_DATA_INIT: never
      APP_FLYWAY_ENABLED: 'true'
      APP_ENV: local