version: '3.3'

services:
  mongo:
    image: mrazjava/booklink-mongo:202008-4.4.0
    ports:
      - 127.0.0.1:27017:27017/tcp
    environment:
      MONGO_INITDB_DATABASE: openlibrary
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
  pg:
    image: mrazjava/booklink-postgres:202009-12.2
    ports:
      - 127.0.0.1:5432:5432
