version: '3.3'

# FYI: comment out tmpfs section to retain database(s) between sandbox runs
# by default databases are temporary for the lifecycle of a container since
# different versions can be requested on each sandbox run

services:
  mongo:
    image: docker.io/${OL_MONGO_IMG}:${OL_MONGO_IMG_TAG}
    container_name: BL_mongo
    tmpfs:
      - /data/db
      - /data/configdb
    ports:
      - ${BL_M_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: openlibrary
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
  pg:
    image: docker.io/${BE_PG_IMG}:${BE_PG_IMG_TAG}
    container_name: BL_pg
    ports:
      - ${BL_P_PORT}:5432
    environment:
      POSTGRES_DB: booklink
      POSTGRES_USER: bookworm
      POSTGRES_PASSWORD: BL
  pginit:
    image: docker.io/mrazjava/booklink-sandbox-pg-init
    container_name: BL_pginit
    depends_on:
      - "pg"
    environment:
      BL_DB: booklink
      BL_DB_SCHEMA: ${DB_SCHEMA}
      BL_DB_HOST: pg
      BL_DB_PORT: ${BL_P_PORT}
      BL_DB_USER: bookworm
      PGPASSWORD: BL