spring:
  data:
    cassandra:
      keyspaceName: booklink
      contactPoints: 127.0.0.1
      username: cassandra
      password: cassandra
      port: 9042
      schemaAction: CREATE_IF_NOT_EXISTS