FROM library/mongo:4.4.0-bionic

ENV MONGO_INITDB_DATABASE=openlibrary
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=pass123

COPY openlibrary-mongo.archive /tmp/mongodump/
COPY mongo-init.sh /docker-entrypoint-initdb.d/
CMD chmod +x /docker-entrypoint-initdb.d/mongo-init.sh
CMD ["mongod"]